config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'page/index'

  resources :productos do
  member do
    get :muestra_pdf
  end
end
  
  
  root to: 'visitors#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/producto.rb
class Producto < ApplicationRecord
	validates :codigo, uniqueness: true
	validates :codigo, :descripcion, :precio, presence: true
	has_attached_file :imagen, styles: { medium: "300x300", thumb: "100x100" }, default_url: "/images/no-existe.png"
  	validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\z/

  	has_attached_file :pdf, default_url: "/images/no-existe.png", path: ":rails_root/pdf/:id/:filename",   url: ":rails_root/pdf/:id/:filename"

    validates_attachment_content_type :pdf, content_type: ['application/pdf']            	

    def url_pdf
    	 Rails.root.join("pdf/",self.id.to_s,self.pdf_file_name||="nofile.pdf").to_s#agregarmos la ruta url con el nombre dle archivo
    end
	
end

app/models/user.rb
class User < ApplicationRecord

  validates :first_name,
            presence: true
  validates :last_name,
            presence: true
  validates :email,
            presence: true,
            uniqueness: true,
            format: {
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            }
  def to_s
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy, :muestra_pdf]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.paginate(:page=>params[:page], :per_page => 10)
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  def muestra_pdf
    #validar primero si el archivo @producto.url_pdf existe
    send_file @producto.url_pdf, type: 'application/pdf', disposition: 'inline' #llama al controlador para enviar archivo
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:codigo, :descripcion, :precio, :observaciones, :activo, :imagen, :pdf)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :password, :password_confirmation)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<div class="container">
  <hr>
  <footer>
      <div class="row">
          <div class="col-lg-12">
              <p>Copyright &copy; Infile</p>
          </div>
      </div>
  </footer>
</div>
<!-- /.container -->

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
        <li>
            <%= link_to 'Services', page_path('services') %>
        </li>
        <li>
            <%= link_to 'Contact', page_path('contact') %>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Portfolio <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>
                    <%= link_to '1 Column Portfolio', page_path('portfolio-1-col') %>
                </li>
                <li>
                    <%= link_to '2 Column Portfolio', page_path('portfolio-2-col') %>
                </li>
                <li>
                    <%= link_to '3 Column Portfolio', page_path('portfolio-3-col') %>
                </li>
                <li>
                    <%= link_to '4 Column Portfolio', page_path('portfolio-4-col') %>
                </li>
                <li>
                    <%= link_to 'Single Portfolio Item', page_path('portfolio-item') %>
                </li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>
                    <%= link_to 'Blog Home 1', page_path('blog-home-1') %>
                </li>
                <li>
                    <%= link_to 'Blog Home 2', page_path('blog-home-2') %>
                </li>
                <li>
                    <%= link_to 'Blog Post', page_path('blog-post') %>
                </li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Other Pages <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>
                    <%= link_to 'Full Width Page', page_path('full-width') %>
                </li>
                <li>
                    <%= link_to 'Sidebar Page', page_path('sidebar') %>
                </li>
                <li>
                    <%= link_to 'FAQ', page_path('faq') %>
                </li>
                <li>
                    <%= link_to '404', page_path('404') %>
                </li>
                <li>
                    <%= link_to 'Pricing Table', page_path('pricing') %>
                </li>
            </ul>
        </li>

         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Mantenimientos <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>
                    <%= link_to 'productos', 'productos' %>
                </li>
                
            </ul>
        </li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "My Application" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "My Application" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/page/index.html.erb
<h1>Page#index</h1>
<p>Find me in app/views/page/index.html.erb</p>

app/views/pages/404.html.erb
<!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">404
                <small>Page Not Found</small>
            </h1>
            <ol class="breadcrumb">
                <li><%= link_to 'Home', root_path %>
                </li>
                <li class="active">404</li>
            </ol>
        </div>
    </div>
    <!-- /.row -->

    <div class="row">

        <div class="col-lg-12">
            <div class="jumbotron">
                <h1><span class="error-404">404</span>
                </h1>
                <p>The page you're looking for could not be found. Here are some helpful links to get you back on track:</p>
                <ul>
                    <li>
                        <%= link_to 'Home', root_path %>
                    </li>
                    <li>
                        <%= link_to 'About', page_path('about') %>
                    </li>
                    <li>
                        <%= link_to 'Services', page_path('services') %>
                    </li>
                    <li>
                        <%= link_to 'Contact', page_path('contact') %>
                    </li>
                    <li>
                        Portfolio
                        <ul>
                            <li>
                              <%= link_to '1 Column Portfolio', page_path('portfolio-1-col') %>
                            </li>
                            <li>
                              <%= link_to '2 Column Portfolio', page_path('portfolio-2-col') %>
                            </li>
                            <li>
                              <%= link_to '3 Column Portfolio', page_path('portfolio-3-col') %>
                            </li>
                            <li>
                              <%= link_to '4 Column Portfolio', page_path('portfolio-4-col') %>
                            </li>
                        </ul>
                    </li>
                    <li>
                        Blog
                        <ul>
                            <li>
                              <%= link_to 'Blog Home 1', page_path('blog-home-1') %>
                            </li>
                            <li>
                              <%= link_to 'Blog Home 2', page_path('blog-home-2') %>
                            </li>
                            <li>
                              <%= link_to 'Blog Post', page_path('blog-post') %>
                            </li>
                        </ul>
                    </li>
                    <li>
                        Other Pages
                        <ul>
                            <li>
                              <%= link_to 'Full Width Page', page_path('full-width') %>
                            </li>
                            <li>
                              <%= link_to 'Sidebar Page', page_path('sidebar') %>
                            </li>
                            <li>
                              <%= link_to 'FAQ', page_path('faq') %>
                            </li>
                            <li>
                              <%= link_to '404', page_path('404') %>
                            </li>
                            <li>
                              <%= link_to 'Pricing Table', page_path('pricing') %>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>

    </div>

</div>
<!-- /.container -->

app/views/pages/about.html.erb
<!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">About
                <small>Subheading</small>
            </h1>
            <ol class="breadcrumb">
                <li><%= link_to 'Home', root_path %>
                </li>
                <li class="active">About</li>
            </ol>
        </div>
    </div>
    <!-- /.row -->

    <!-- Intro Content -->
    <div class="row">
        <div class="col-md-6">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </div>
        <div class="col-md-6">
            <h2>About Modern Business</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed voluptate nihil eum consectetur similique? Consectetur, quod, incidunt, harum nisi dolores delectus reprehenderit voluptatem perferendis dicta dolorem non blanditiis ex fugiat.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe, magni, aperiam vitae illum voluptatum aut sequi impedit non velit ab ea pariatur sint quidem corporis eveniet. Odit, temporibus reprehenderit dolorum!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et, consequuntur, modi mollitia corporis ipsa voluptate corrupti eum ratione ex ea praesentium quibusdam? Aut, in eum facere corrupti necessitatibus perspiciatis quis?</p>
        </div>
    </div>
    <!-- /.row -->

    <!-- Team Members -->
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">Our Team</h2>
        </div>
        <div class="col-md-4 text-center">
            <div class="thumbnail">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                <div class="caption">
                    <h3>John Smith<br>
                        <small>Job Title</small>
                    </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                    <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-4 text-center">
            <div class="thumbnail">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                <div class="caption">
                    <h3>John Smith<br>
                        <small>Job Title</small>
                    </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                    <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-4 text-center">
            <div class="thumbnail">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                <div class="caption">
                    <h3>John Smith<br>
                        <small>Job Title</small>
                    </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                    <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-4 text-center">
            <div class="thumbnail">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                <div class="caption">
                    <h3>John Smith<br>
                        <small>Job Title</small>
                    </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                    <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-4 text-center">
            <div class="thumbnail">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                <div class="caption">
                    <h3>John Smith<br>
                        <small>Job Title</small>
                    </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                    <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-4 text-center">
            <div class="thumbnail">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                <div class="caption">
                    <h3>John Smith<br>
                        <small>Job Title</small>
                    </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                    <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->

    <!-- Our Customers -->
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">Our Customers</h2>
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6">
            <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6">
            <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6">
            <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6">
            <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6">
            <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6">
            <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
        </div>
    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

app/views/pages/full-width.html.erb
<!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Full Width Page
                <small>Subheading</small>
            </h1>
            <ol class="breadcrumb">
                <li><%= link_to 'Home', root_path %>
                </li>
                <li class="active">Full Width Page</li>
            </ol>
        </div>
    </div>
    <!-- /.row -->

    <!-- Content Row -->
    <div class="row">
        <div class="col-lg-12">
            <p>Most of Start Bootstrap's unstyled templates can be directly integrated into the Modern Business template. You can view all of our unstyled templates on our website at <a href="http://startbootstrap.com/template-categories/unstyled">http://startbootstrap.com/template-categories/unstyled</a>.</p>
        </div>
    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

app/views/productos/_form.html.erb
<%= simple_form_for(@producto) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :codigo %>
    <%= f.input :descripcion %>
    <%= f.input :precio %>
    <%= f.input :observaciones %>
    <%= f.input :activo %>
    <%= f.input :imagen, as: :file %>
    <%= f.input :pdf, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editar Producto</h1>

<%= render 'form', producto: @producto %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Productos</h1>
<center>
<%= link_to 'Nuevo producto', new_producto_path, class: 'btn btn-primary fa fa-plus' %>
</center>

<br>
<div class="table-responsive">
<table class="table table-hover table-bordered">
  <thead>
    <tr>
    
      <th><strong><center>Imagen</strong></center></th>
      <th><strong><center>Codigo</strong></center></th>
      <th><strong><center>Descripcion</strong></center></th>
      <th><strong><center>Precio</strong></center></th>
      <th><strong><center>Observaciones</strong></center></th>
      <th><strong><center>Activo</strong></center></th>
      <th><strong><center>Catalogo</strong></center></th>
      <th><strong><center>Opciones </strong></center></th>

    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><img src="<%= producto.imagen %>" width="50" height="50"></td>
        <td><%= producto.codigo %></td>
        <td><%= producto.descripcion %></td>
        <td><%= producto.precio %></td>
        <td><%= producto.observaciones %></td>
        <% if producto.activo == true %>
          <td> ACTIVO</td>
        <% else %>
          <td>INACTIVO</td>
        <% end %>
        <td> <%= link_to 'Descargar', muestra_pdf_producto_path(producto) , class: 'btn btn-primary fa fa-download' %> </td>
        <td><%= link_to 'Detalles', producto, class: 'btn btn-default fa fa-eye' %>
        <%= link_to 'Editar', edit_producto_path(producto) , class: 'btn btn-warning fa fa-edit' %>
        <%= link_to 'Eliminar', producto, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger fa fa-close' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<center>
<%= will_paginate @collection, renderer: BootstrapPagination::Rails, :previous_label => 'Anterior', :next_label => 'Siguiente'  %>
</center>
</div>

<br>

app/views/productos/new.html.erb
<h1>Nuevo Producto</h1>

<%= render 'form', producto: @producto %>

<%= link_to 'Back', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @producto.codigo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @producto.descripcion %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @producto.precio %>
</p>

<p>
  <strong>Observaciones:</strong>
  <%= @producto.observaciones %>
</p>

<p>
  <strong>Activo:</strong>
  <%= @producto.activo %>
</p>
<p>
  <strong>Imagen:</strong>
  <img src="<%= @producto.imagen %>" width="50" height="50">
</p>

<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :password %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>